// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBo0L1sZbmxhEV4X-HQvcF4I6USugLfAS4',
//     appId: '1:135767615744:android:f76d33f9e3f1728a686be5',
//     messagingSenderId: '135767615744',
//     projectId: 'dict-app-cbf85',
//     storageBucket: 'dict-app-cbf85.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyApAYPBmKQDsw6yzI-U_vzROylsHyjZ2Zg',
//     appId: '1:135767615744:ios:4956c002ab69e337686be5',
//     messagingSenderId: '135767615744',
//     projectId: 'dict-app-cbf85',
//     storageBucket: 'dict-app-cbf85.firebasestorage.app',
//     iosBundleId: 'com.daikikaneda.dictApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyApAYPBmKQDsw6yzI-U_vzROylsHyjZ2Zg',
//     appId: '1:135767615744:ios:4956c002ab69e337686be5',
//     messagingSenderId: '135767615744',
//     projectId: 'dict-app-cbf85',
//     storageBucket: 'dict-app-cbf85.firebasestorage.app',
//     iosBundleId: 'com.daikikaneda.dictApp',
//   );

// }